

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TelefonSatisTakipSistemi.Models.Entity
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DbTelefonSatisEntities : DbContext
{
    public DbTelefonSatisEntities()
        : base("name=DbTelefonSatisEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<TBLADMİN> TBLADMİN { get; set; }

    public virtual DbSet<TBLKATEGORİ> TBLKATEGORİ { get; set; }

    public virtual DbSet<TBLMUSTERİ> TBLMUSTERİ { get; set; }

    public virtual DbSet<TBLPERSONEL> TBLPERSONEL { get; set; }

    public virtual DbSet<TBLSATİSDETAY> TBLSATİSDETAY { get; set; }

    public virtual DbSet<TBLSATİSLAR> TBLSATİSLAR { get; set; }

    public virtual DbSet<TBLURUNLER> TBLURUNLER { get; set; }

}

}

