//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonSatisTakipSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLMUSTERİ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMUSTERİ()
        {
            this.TBLSATİSLAR = new HashSet<TBLSATİSLAR>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="Müşteri adını boş geçemezsiniz.")]
        public string AD { get; set; }
        [Required(ErrorMessage ="Müşteri soyadını boş geçemezsiniz.")]
        public string SOYAD { get; set; }
        [Required(ErrorMessage ="Şehir bilgisini boş geçemezsiniz.")]
        public string SEHİR { get; set; }
        [Required(ErrorMessage = "Telefon numarası boş geçemezsiniz.")]
        public string TELEFON { get; set; }
        [Required(ErrorMessage = "E-posta adresi boş geçemezsiniz.")]
        [EmailAddress(ErrorMessage = "Geçersiz e-posta formatı!")]
        public string EPOSTA { get; set; }
        [Required(ErrorMessage = "Adres alanı boş geçemezsiniz.")]
        public string ADRES { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATİSLAR> TBLSATİSLAR { get; set; }
    }
}
