//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonSatisTakipSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLPERSONEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPERSONEL()
        {
            this.TBLSATİSLAR = new HashSet<TBLSATİSLAR>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Personel adını boş geçemezsiniz.")]
        public string AD { get; set; }
        [Required(ErrorMessage = "Personel soyadını boş geçemezsiniz.")]
        public string SOYAD { get; set; }
        [Required(ErrorMessage = "Departman adını boş geçemezsiniz.")]
        public string DEPARTMAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATİSLAR> TBLSATİSLAR { get; set; }
    }
}
