//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonSatisTakipSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSATİSDETAY
    {
        public int ID { get; set; }
        public Nullable<int> SATİSID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> FİYAT { get; set; }
    
        public virtual TBLSATİSLAR TBLSATİSLAR { get; set; }
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
