
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TelefonSatisTakipSistemi.Models.Entity
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLURUNLER
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLURUNLER()
        {

            this.TBLSATİSDETAY = new HashSet<TBLSATİSDETAY>();

        }


        public int ID { get; set; }
        [Required(ErrorMessage = "Markayı boş geçemezsiniz.")]
        public string MARKA { get; set; }
        [Required(ErrorMessage = "Model alanını boş geçemezsiniz.")]

        public string MODEL { get; set; }
        [Required(ErrorMessage = "Lütfen bir kategori seçiniz.")]

        public Nullable<int> KATEGORİ { get; set; }
        [Required(ErrorMessage = "Stok miktarını boş geçemezsiniz.")]
        [Range(0, 5000, ErrorMessage = "Stok 0 - 5000 arasında olmalıdır.")]

        public Nullable<int> STOK { get; set; }
        [Required(ErrorMessage = "Alış fiyatını boş geçemezsiniz.")]

        public Nullable<decimal> ALİSFİYATİ { get; set; }
        [Required(ErrorMessage = "Satış fiyatını boş geçilemez.")]

        public Nullable<decimal> SATİSFİYATİ { get; set; }

        public string ACİKLAMA { get; set; }

        public Nullable<bool> DURUM { get; set; }



        public virtual TBLKATEGORİ TBLKATEGORİ { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<TBLSATİSDETAY> TBLSATİSDETAY { get; set; }

    }

}
